Error 1:Generated script 'C:\\Grohit_win_build\\jiva_buildout\\bin\\zeo_srv_service'.
Installing mssqlconf.
While:
  Installing mssqlconf.

  An internal error occurred due to a bug in either zc.buildout or in a
  recipe being used:
  Traceback (most recent call last):
    File "c:\grohit_win_build\jiva_buildout\tmp\tmpflbgal\zc.buildout-1.7.1-py2.6.
    egg\zc\buildout\buildout.py", line 1866, in main
      File "c:\grohit_win_build\jiva_buildout\tmp\tmpflbgal\zc.buildout-1.7.1-py2.6.
      egg\zc\buildout\buildout.py", line 625, in install
        File "c:\grohit_win_build\jiva_buildout\tmp\tmpflbgal\zc.buildout-1.7.1-py2.6.
	egg\zc\buildout\buildout.py", line 1345, in _call
	  File "build\bdist.win32\egg\zeomega\recipe\winodbcdsn\__init__.py", line 102,
	  in install
	  WindowsError: [Error 5] Access is denied

Solution:  dont execute on git bash except for git commands.
	 


-------------------------------------------------------------------------------	 
Error 2:C:\Grohit_win_build\jiva_buildout>bin\zeo_srv_service.exe start
Starting service ZEO_-1219517520
Error starting service: The service did not respond to the start or control requ
est in a timely fashion.


Solution :python26.dll for python installed directory was not in system32 directory.so you need to copy that file 
into system32.


-------------------------------------------------------------------------------------------------------------
C:\Grohit_build_win\jiva_buildout>bin\zope_c1.exe fg
Traceback (most recent call last):
  File "c:\grohit_build_win\jiva_buildout\eggs\zope2-2.12.22-py2.6-win32.egg\Zop
e2\Startup\run.py", line 56, in <module>
    run()
  File "c:\grohit_build_win\jiva_buildout\eggs\zope2-2.12.22-py2.6-win32.egg\Zop
e2\Startup\run.py", line 17, in run
    import Zope2.Startup
  File "c:\Grohit_build_win\jiva_buildout\eggs\Zope2-2.12.22-py2.6-win32.egg\Zop
e2\__init__.py", line 60, in <module>
    from Zope2.Startup.run import configure
  File "c:\Grohit_build_win\jiva_buildout\eggs\Zope2-2.12.22-py2.6-win32.egg\Zop
e2\Startup\__init__.py", line 27, in <module>
    from zope.event import notify
ImportError: No module named event




Solution:


---------------------------------------------------------------------------------------------------------------
